/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Wizard = React.memo(function Wizard(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models11/wizard-transformed.glb");

  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.position.y =
      -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;
  });

  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      position={[-1.057, -15, 0.001]}
      scale={[-0.28, 0.20, 0.025]}
      rotation={[-1.65, -0.05, -0.19]}


    >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_Planks_0.geometry}
              material={materials.Planks}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_Walls_0.geometry}
              material={materials.Walls}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_Lights_0.geometry}
              material={materials.Lights}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_Window_0.geometry}
              material={materials.Window}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_Floor_0.geometry}
              material={materials.Floor}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_Frame_0.geometry}
              material={materials.Frame}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_Backdrop_0.geometry}
              material={materials.Backdrop}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_TVScreen_0.geometry}
              material={materials.TVScreen}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_Sofa_0.geometry}
              material={materials.Sofa}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_Carpet_0.geometry}
              material={materials.Carpet}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_EndTable_0.geometry}
              material={materials.EndTable}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_CoffeeTable_0.geometry}
              material={materials.CoffeeTable}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_Pot_0.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_Pebbles_0.geometry}
              material={materials.Pebbles}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_Painting_0.geometry}
              material={materials.Painting}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_Door_0.geometry}
              material={materials.Door}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_Leaves_0.geometry}
              material={materials.Leaves}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Modern_Living_Room_Bark_0.geometry}
              material={materials.Bark}
            />
    </group>
  );
});

export default Wizard;
useGLTF.preload("/models/wizard-transformed.glb");
